spring:
  application:
    name: portal
  datasource:
    dynamic:
      primary: portal


springdoc:
  swagger-ui:
    path: /portal/swagger-ui/index.html
  api-docs:
    path: /portal/v3/api-docs

management:
  health:
    ldap:
      enabled: false
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8091